// <auto-generated />
using System;
using Cv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cv.Data.Migrations
{
    [DbContext(typeof(CvDbContext))]
    [Migration("20261008070628_RequireRendersToPublish")]
    partial class RequireRendersToPublish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cv")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cv.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_log_actor_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_log_created_at");

                    b.ToTable("audit_log", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvNode", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Attrs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attrs")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sort_key")
                        .UseCollation("C");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_code");

                    b.HasKey("VersionId", "NodeId")
                        .HasName("pk_cv_nodes");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_cv_nodes_type_code");

                    b.HasIndex("VersionId", "ParentNodeId", "SortKey")
                        .IsUnique()
                        .HasDatabaseName("ux_cv_nodes_sibling_order");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("VersionId", "ParentNodeId", "SortKey"), false);

                    b.ToTable("cv_nodes", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvNodeContent", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("LocaleCode")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsOmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_omitted");

                    b.Property<byte[]>("SourceHash")
                        .HasColumnType("bytea")
                        .HasColumnName("source_hash");

                    b.HasKey("VersionId", "NodeId", "LocaleCode")
                        .HasName("pk_cv_node_contents");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_cv_node_contents_locale");

                    b.ToTable("cv_node_contents", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvPublication", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<bool>("LocalePublishable")
                        .HasColumnType("boolean")
                        .HasColumnName("locale_publishable");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<Guid?>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Seq")
                        .HasName("pk_cv_publications");

                    b.HasIndex("PublishedBy")
                        .HasDatabaseName("ix_cv_publications_published_by");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_cv_publications_version_id");

                    b.HasIndex("LocaleCode", "LocalePublishable", "Seq")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_cv_publications_locale_history");

                    b.ToTable("cv_publications", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvRender", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<string>("LocaleCode")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("RendererVersion")
                        .HasColumnType("text")
                        .HasColumnName("renderer_version");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("VersionId", "LocaleCode", "Format", "RendererVersion")
                        .HasName("pk_cv_renders");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_cv_renders_locale");

                    b.ToTable("cv_renders", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_version_id");

                    b.Property<Guid?>("RestoredFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("restored_from_version_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_cv_versions");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_cv_versions_created_by");

                    b.HasIndex("PreviousVersionId")
                        .IsUnique()
                        .HasDatabaseName("ux_cv_versions_previous_version_id");

                    b.HasIndex("RestoredFromVersionId")
                        .HasDatabaseName("ix_cv_versions_restored_from_version_id");

                    b.HasIndex("VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_cv_versions_version_number");

                    b.ToTable("cv_versions", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.Locale", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsPublishable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_publishable");

                    b.Property<bool>("IsSource")
                        .HasColumnType("boolean")
                        .HasColumnName("is_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_locales");

                    b.HasAlternateKey("Code", "IsPublishable")
                        .HasName("ak_locales_code_is_publishable");

                    b.ToTable("locales", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.NodeType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasText")
                        .HasColumnType("boolean")
                        .HasColumnName("has_text");

                    b.HasKey("Code")
                        .HasName("pk_node_types");

                    b.ToTable("node_types", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.NodeTypeChild", b =>
                {
                    b.Property<string>("ParentType")
                        .HasColumnType("text")
                        .HasColumnName("parent_type");

                    b.Property<string>("ChildType")
                        .HasColumnType("text")
                        .HasColumnName("child_type");

                    b.HasKey("ParentType", "ChildType")
                        .HasName("pk_node_type_children");

                    b.HasIndex("ChildType")
                        .HasDatabaseName("ix_node_type_children_child_type");

                    b.ToTable("node_type_children", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "cv");
                });

            modelBuilder.Entity("Cv.Data.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("Cv.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_actor");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvNode", b =>
                {
                    b.HasOne("Cv.Data.Entities.NodeType", null)
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_nodes_type");

                    b.HasOne("Cv.Data.Entities.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_nodes_version");

                    b.HasOne("Cv.Data.Entities.CvNode", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "ParentNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cv_nodes_parent");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvNodeContent", b =>
                {
                    b.HasOne("Cv.Data.Entities.Locale", null)
                        .WithMany()
                        .HasForeignKey("LocaleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_node_contents_locale");

                    b.HasOne("Cv.Data.Entities.CvNode", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_node_contents_node");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvPublication", b =>
                {
                    b.HasOne("Cv.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_publications_published_by");

                    b.HasOne("Cv.Data.Entities.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cv_publications_version");

                    b.HasOne("Cv.Data.Entities.Locale", null)
                        .WithMany()
                        .HasForeignKey("LocaleCode", "LocalePublishable")
                        .HasPrincipalKey("Code", "IsPublishable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_publications_locale");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvRender", b =>
                {
                    b.HasOne("Cv.Data.Entities.Locale", null)
                        .WithMany()
                        .HasForeignKey("LocaleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_renders_locale");

                    b.HasOne("Cv.Data.Entities.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_renders_version");
                });

            modelBuilder.Entity("Cv.Data.Entities.CvVersion", b =>
                {
                    b.HasOne("Cv.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cv_versions_created_by");

                    b.HasOne("Cv.Data.Entities.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cv_versions_previous_version");

                    b.HasOne("Cv.Data.Entities.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("RestoredFromVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cv_versions_restored_from_version");
                });

            modelBuilder.Entity("Cv.Data.Entities.NodeTypeChild", b =>
                {
                    b.HasOne("Cv.Data.Entities.NodeType", null)
                        .WithMany()
                        .HasForeignKey("ChildType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_node_type_children_child_type");

                    b.HasOne("Cv.Data.Entities.NodeType", null)
                        .WithMany()
                        .HasForeignKey("ParentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_node_type_children_parent_type");
                });
#pragma warning restore 612, 618
        }
    }
}
